### PR TITLE
Miscellaneous PR feedback fixes

### LINKED ISSUE #417: [Upstreaming] Update `PosTest` to `PrismPosTest`
https://github.com/sorbet/sorbet/pull/8122#discussion_r1765442564

### PR DESCRIPTION
**Pull request by amomchilov**
Fixes several of Jake's comments from [his initial review of my first PR](https://github.com/sorbet/sorbet/pull/8122)

Fixes #417

### CODE REVIEW

**Comment by amomchilov** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Shopify/sorbet/588?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#588** <a href="https://app.graphite.dev/github/pr/Shopify/sorbet/588?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/Shopify/sorbet/588?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#587** <a href="https://app.graphite.dev/github/pr/Shopify/sorbet/587?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#581** <a href="https://app.graphite.dev/github/pr/Shopify/sorbet/581?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#579** <a href="https://app.graphite.dev/github/pr/Shopify/sorbet/579?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#578** <a href="https://app.graphite.dev/github/pr/Shopify/sorbet/578?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#576** <a href="https://app.graphite.dev/github/pr/Shopify/sorbet/576?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `prism-squashed`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: parser/prism/Parser.h [hunk 1]
```diff
@@ -96,6 +96,8 @@ class ParseResult final {
 
     ParseResult(const ParseResult &) = delete;            // Copy constructor
     ParseResult &operator=(const ParseResult &) = delete; // Copy assignment
+    ParseResult(ParseResult &&) = default;                // Move constructor
+    ParseResult &operator=(ParseResult &&) = default;     // Move assignment
```
Comment (amomchilov) [inline parser/prism/Parser.h:100]: https://github.com/sorbet/sorbet/pull/8122#discussion_r1765518813

File: parser/prism/Translator.cc [hunk 2]
```diff
@@ -3,18 +3,15 @@
 
 template class std::unique_ptr<sorbet::parser::Node>;
 
-using std::is_same_v;
-using std::make_unique;
-using std::move;
-using std::unique_ptr;
+using namespace std;
```
Comment (amomchilov) [inline parser/prism/Translator.cc:6]: https://github.com/sorbet/sorbet/pull/8122#discussion_r1765520596

File: break.rb
Comment (amomchilov) [inline break.rb:1]: https://github.com/sorbet/sorbet/pull/8122#discussion_r1765452548

**Review by KaanOzkan — APPROVED** [review]
Is `break.rb` intentional?

**Comment by amomchilov** [comment]
Yep, I checked it in by accident (at the root of the repo), and this PR pulls it back out

**Comment by amomchilov** [comment]
### Merge activity

* **Jul 10, 7:18 PM UTC**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Shopify/sorbet/588).
