### PR TITLE
Fix failing local_vars test by translating post params

### LINKED ISSUE #381: Investigate failing local_vars test

### PR DESCRIPTION
**Pull request by egiurleo**
Closes #381
Opens #393, having to do with the handling of `**nil` as a post param.

### Motivation
So uh... I think we (*I*) forgot that post params exist 😁 

### Test plan
See included automated tests.

### CODE REVIEW

File: parser/prism/Translator.cc [hunk 1]
```diff
@@ -1016,21 +1016,36 @@ unique_ptr<parser::Node> Translator::translate(pm_node_t *node) {
...
+            for (auto &post : posts) {
+                switch (PM_NODE_TYPE(post)) {
+                    case PM_NO_KEYWORDS_PARAMETER_NODE: { // `**nil`
+                        params.emplace_back(translateSimpleKeyword<parser::Kwnilarg>(post));
+                        break;
+                    }
+                    default:
+                        params.emplace_back(translate(post));
+                }
+            }
```
Comment (egiurleo) [inline parser/prism/Translator.cc:1047]: @st0012 I'm curious to hear your thoughts on this --

In the case where `**nil` is passed as a post argument (e.g. `def foo(**nil, **nil); end`), the legacy parser and Prism have different behavior:

- The Sorbet parser will [replace the entire tree with a `Nil` node](https://sorbet.run/?arg=--print&arg=parse-tree#%23%20typed%3A%20true%0A%0Adef%20foo%28**nil%2C%20**nil%29%3B%20end%0A)
- Prism will replace the `**nil` post parameter with a `NoKeywordsParameterNode` but leave the rest of the tree the same.

I added handling here to prevent some of the tests from crashing, but it introduces a difference in the parse trees.

Are you okay leaving this as is for now and revisiting once we do more error handling work?

**Review by st0012 — APPROVED** [review]
