### PR TITLE
Fix splat arg translation

### LINKED ISSUE #357: //test:test_PosTests/testdata/desugar/star_in_block_arg

### PR DESCRIPTION
**Pull request by st0012**
### Motivation

When the splat arg's expression is an `Arg`, we need to translate it to a `Restarg` instead of a `SplatLhs`.

Closes #357

### Test plan

See included automated tests.

### CODE REVIEW

File: parser/prism/Translator.cc [hunk 1]
```diff
@@ -1866,7 +1866,18 @@ template <typename PrismNode> std::unique_ptr<parser::Mlhs> Translator::translat
                 auto location = translateLoc(splatNode->base.location);
                 auto expr = translate(splatNode->expression);
 
-                sorbetLhs.emplace_back(make_unique<parser::SplatLhs>(location, move(expr)));
+                std::unique_ptr<parser::Node> sorbetPlatNode;
```
Comment (egiurleo) [inline parser/prism/Translator.cc:1869]:
```suggestion
                std::unique_ptr<parser::Node> sorbetSplatNode;
```

File: parser/prism/Translator.cc [hunk 2]
```diff
@@ -1866,7 +1866,18 @@ template <typename PrismNode> std::unique_ptr<parser::Mlhs> Translator::translat
...
+
+                auto argNode = dynamic_cast<parser::Arg *>(expr.get());
```
Comment (egiurleo) [inline parser/prism/Translator.cc:1871]: Out of curiosity, what is the type of `expr` here? I'm wondering why we should `dynamic_cast` to a Sorbet parser type here rather than using some information in `splatNode->expression` and then translating directly into a `parser::Arg`?

**Review by egiurleo — COMMENTED** [review]
This makes a lot of sense to me but I have a small suggestion and a question!

File: parser/prism/Translator.cc (hunk 2 above)
Comment (amomchilov) [inline parser/prism/Translator.cc:1871]: I'd like to avoid doing dynamic type checks if possible. I'm thinking: rather than checking the type of the result on the way out of `translate()`, can we instead check something about the input before `translate()` instead?

From what I can tell, `translate()` can only return a `pasrser::Arg` in the `case PM_REQUIRED_PARAMETER_NODE`, so we do a (faster) check for that instead:

```c++
auto expr = translate(splatNode->expression);

if (PM_NODE_TYPE_P(splatNode->expression, PM_REQUIRED_PARAMETER_NODE)) {
    sorbetLhs.emplace_back(make_unique<parser::SplatLhs>(location, move(expr));
} else {
    sorbetLhs.emplace_back(make_unique<parser::Restarg>(location, argNode->name, argNode->loc));
}
```

WDYT?

Some added comments to explain the reasoning behind the `if`/`else` would be nice, too.
